### ISSUE TITLE
This icon file is not used

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-Frontend#725] opened 2023-09-09 11:51 UTC
https://github.com/tokitou-san/CoreProject-Frontend/blob/247a984727dfd5b431c4c512f0ad654dce524497/src/lib/icons/list_linear_gradient.svelte#L1-L66

**Comment by tokitou-san** [comment] 2023-09-12 13:46
Duplicate of #726

**Closed by tokitou-san** 2023-09-12 13:46 UTC
